
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
#
# Initial commit
#
# Changes to be committed:
#	new file:   .gitignore
#	new file:   Gemfile
#	new file:   Gemfile.lock
#	new file:   README.rdoc
#	new file:   Rakefile
#	new file:   app/assets/images/.keep
#	new file:   app/assets/javascripts/application.js
#	new file:   app/assets/javascripts/bets.coffee
#	new file:   app/assets/javascripts/sessions.coffee
#	new file:   app/assets/javascripts/users.coffee
#	new file:   app/assets/stylesheets/application.css
#	new file:   app/assets/stylesheets/bets.scss
#	new file:   app/assets/stylesheets/sessions.scss
#	new file:   app/assets/stylesheets/users.scss
#	new file:   app/controllers/application_controller.rb
#	new file:   app/controllers/bets_controller.rb
#	new file:   app/controllers/concerns/.keep
#	new file:   app/controllers/sessions_controller.rb
#	new file:   app/controllers/users_controller.rb
#	new file:   app/helpers/application_helper.rb
#	new file:   app/helpers/bets_helper.rb
#	new file:   app/helpers/sessions_helper.rb
#	new file:   app/helpers/users_helper.rb
#	new file:   app/mailers/.keep
#	new file:   app/models/.keep
#	new file:   app/models/bet.rb
#	new file:   app/models/concerns/.keep
#	new file:   app/models/user.rb
#	new file:   app/views/bets/feed.html.erb
#	new file:   app/views/bets/new.html.erb
#	new file:   app/views/layouts/application.html.erb
#	new file:   app/views/sessions/new.html.erb
#	new file:   app/views/users/new.html.erb
#	new file:   bin/bundle
#	new file:   bin/rails
#	new file:   bin/rake
#	new file:   bin/setup
#	new file:   bin/spring
#	new file:   config.ru
#	new file:   config/application.rb
#	new file:   config/boot.rb
#	new file:   config/database.yml
#	new file:   config/environment.rb
#	new file:   config/environments/development.rb
#	new file:   config/environments/production.rb
#	new file:   config/environments/test.rb
#	new file:   config/initializers/assets.rb
#	new file:   config/initializers/backtrace_silencers.rb
#	new file:   config/initializers/cookies_serializer.rb
#	new file:   config/initializers/filter_parameter_logging.rb
#	new file:   config/initializers/inflections.rb
#	new file:   config/initializers/mime_types.rb
#	new file:   config/initializers/session_store.rb
#	new file:   config/initializers/wrap_parameters.rb
#	new file:   config/locales/en.yml
#	new file:   config/routes.rb
#	new file:   config/secrets.yml
#	new file:   db/migrate/20150618205046_create_users.rb
#	new file:   db/migrate/20150618215834_add_role_to_users.rb
#	new file:   db/migrate/20150618224508_create_bets.rb
#	new file:   db/schema.rb
#	new file:   db/seeds.rb
#	new file:   lib/assets/.keep
#	new file:   lib/tasks/.keep
#	new file:   log/.keep
#	new file:   public/404.html
#	new file:   public/422.html
#	new file:   public/500.html
#	new file:   public/favicon.ico
#	new file:   public/robots.txt
#	new file:   test/controllers/.keep
#	new file:   test/controllers/bets_controller_test.rb
#	new file:   test/controllers/sessions_controller_test.rb
#	new file:   test/controllers/users_controller_test.rb
#	new file:   test/fixtures/.keep
#	new file:   test/fixtures/bets.yml
#	new file:   test/fixtures/users.yml
#	new file:   test/helpers/.keep
#	new file:   test/integration/.keep
#	new file:   test/mailers/.keep
#	new file:   test/models/.keep
#	new file:   test/models/bet_test.rb
#	new file:   test/models/user_test.rb
#	new file:   test/test_helper.rb
#	new file:   vendor/assets/javascripts/.keep
#	new file:   vendor/assets/stylesheets/.keep
#
